# Generated by Django 4.2.16 on 2024-11-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='spam_likelihood',
        ),
        migrations.AddField(
            model_name='contact',
            name='spam_marked_count',
            field=models.IntegerField(default=0),
        ),
    ]
