# Generated by Django 4.2.16 on 2024-11-09 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='spam_marked_count',
        ),
        migrations.CreateModel(
            name='SpamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contact')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'unique_together': {('marked_by', 'contact')},
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='spam_marked_by',
            field=models.ManyToManyField(related_name='marked_spam', through='app.SpamDetails', to='app.user'),
        ),
    ]
