# Generated by Django 4.2.16 on 2024-11-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_contact_spam_marked_count_spamdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
